config/routes.rb
Rails.application.routes.draw do
  
  
  
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :newsvilles do
    resources :comments
  end
  root to: 'pages#index'


end

app/models/ability.rb
class Ability
  
include CanCan::Ability
def initialize(user)
  
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)
    if user.admin?
    can :manage, :all
    else
    can :update, Newsville do |news|
    news.user == user
    end
    can :destroy, Newsville do |news|
    news.user == user
    end
    can :update, Comment do |comment|
    comment.user == user
    end
    can :destroy, Comment do |comment|
    comment.user == user
    end
    can :create, Newsville
    can :create, Comment
    can :read, :all
    end
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :newsville
end

app/models/newsville.rb
class Newsville < ActiveRecord::Base
  belongs_to :user
  has_many :comments
  validates :title_url, uniqueness: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable, :confirmable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :newsvilles
  
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, 
  default_url: "nia2.jpg" 
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
    rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path
    flash[:alert] = "Sorry, you are not authorized to access this area!"
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource param_method: :my_sanitizer
  load_and_authorize_resource :through => :current_user
  


  # GET /comments/new
  def new
    @comment = Comment.new
  end


  def create
    @newsville = Newsville.find(params[:newsville_id])
    @comment = @newsville.comments.new(comment_params)
    @comment.user = current_user
    
    respond_to do |format|
      if @comment.save
        format.html { redirect_to @newsville, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end



  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to @comment.newsville, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:newsville_id, :body, :user_id)
    end
    
    def my_sanitizer
      params.require(:comment).permit(:body)
    end
end

app/controllers/newsvilles_controller.rb
class NewsvillesController < ApplicationController
  before_action :set_newsville, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  
  # GET /newsvilles
  # GET /newsvilles.json
  def index

    @newsvilles = Newsville.paginate(page: params[:page], per_page: 20).order("created_at DESC")
  end

  # GET /newsvilles/1
  # GET /newsvilles/1.json
  def show
  end

  # GET /newsvilles/new
  def new
    @newsville = Newsville.new
  end

  # GET /newsvilles/1/edit
  def edit
    authorize! :update, @newsville
  end

  # POST /newsvilles
  # POST /newsvilles.json
  def create
    @newsville = Newsville.new(newsville_params)

    respond_to do |format|
      if @newsville.save
        format.html { redirect_to @newsville, notice: 'Newsville was successfully created.' }
        format.json { render :show, status: :created, location: @newsville }
      else
        format.html { render :new }
        format.json { render json: @newsville.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /newsvilles/1
  # PATCH/PUT /newsvilles/1.json
  def update
    authorize! :update, @newsville
    respond_to do |format|
      if @newsville.update(newsville_params)
        format.html { redirect_to @newsville, notice: 'Newsville was successfully updated.' }
        format.json { render :show, status: :ok, location: @newsville }
      else
        format.html { render :edit }
        format.json { render json: @newsville.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /newsvilles/1
  # DELETE /newsvilles/1.json
  def destroy
    authorize! :destroy, @newsville
    @newsville.destroy
    respond_to do |format|
      format.html { redirect_to newsvilles_url, notice: 'Newsville was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_newsville
      @newsville = Newsville.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def newsville_params
      params.require(:newsville).permit(:title_url, :title, :body, :time, :image_url)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  
  def index
    @newsvilles = Newsville.all.first(4)
    @comments = Comment.last(30)
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(
      :email, 
      :password, 
      :password_confirmation,
      :username,
      :image,
      :url
      )
  end

  def account_update_params
    params.require(:user).permit(
      :email, 
      :password, 
      :password_confirmation, 
      :current_password,
      :username,
      :image,
      :url
      )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/newsvilles_helper.rb
module NewsvillesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/comments/_comment.html.erb
<div class="col-md-12">
  <div class="caption-full">
      <h4 class="pull-right">Was posted <%= time_ago_in_words(comment.created_at) %> ago</h4>
      <h4>Comment by <%= comment.user.username %></h4>
      <%= image_tag comment.user.image.url(:thumb),  class: "img-circle" %>
      <p><%= comment.body %></p>
      <% if can? :destroy, comment %>
      <%= link_to 'Destroy', [comment.newsville, comment], method: :delete, 
        data: { confirm: 'Are you sure?' }, class: "btn btn-primary btn-xs" %>
      <% end %>  
  </div>
</div>
 

app/views/comments/_form.html.erb
<%= simple_form_for(@comment) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :newsville_id %>
    <%= f.input :body %>
    <%= f.association :user %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th>Newsville</th>
      <th>Body</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.newsville_id %></td>
        <td><%= comment.body %></td>
        <td><%= comment.user %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Newsville:</strong>
  <%= @comment.newsville_id %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<p>
  <strong>User:</strong>
  <%= @comment.user %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/_alert.html.erb
<% if notice || alert %>
    <div class="alert <%= notice ? "alert-info" : "" %><%= alert ? "alert-danger" : "" %> alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <div >
            <% if notice %>
                <%= notice %>
            <% elsif alert %>
                <%= alert %>
            <% end %>
        </div>
    </div>
<% end %>

app/views/layouts/_footer.html.erb
<!-- Footer -->
<div class='container'>
  <footer>
      <div class="row">
          <div class="col-lg-12">
              <p>Copyright &copy; Your Website 2014</p>
          </div>
      </div>
      <!-- /.row -->
  </footer>
</div>  

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Newsville", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      
      
      <ul class="nav navbar-nav navbar-right">
        <% if !current_user %>
        <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <li><%= link_to "Sign In", new_user_session_path %></li>
        <% end %>
        <li><%= link_to "Newsvilles", newsvilles_path %></li>
        <% if current_user %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            <%= current_user.username %> <span class="caret"></span></a>
            <% end %>
          <ul class="dropdown-menu">
            <li><%= link_to "Edit my profile", edit_user_registration_path %></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "End my session", destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Scrapeville</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/navbar' %>
  <%= render 'layouts/alert' %>

<div class='container'>
  <%= yield %>
</div>
  <%= render 'layouts/footer' %>
</body>
</html>

app/views/newsvilles/_form.html.erb
<%= simple_form_for(@newsville) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title_url %>
    <%= f.input :title %>
    <%= f.input :body %>
    <%= f.input :time %>
    <%= f.input :image_url %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/newsvilles/edit.html.erb
<h1>Editing Newsville</h1>

<%= render 'form' %>

<%= link_to 'Show', @newsville %> |
<%= link_to 'Back', newsvilles_path %>

app/views/newsvilles/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Welcome to Newsville</h1> 
<div class='text-center'>
  <%= will_paginate @newsvilles, renderer: BootstrapPagination::Rails %>
</div>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Original Story</th>
      <th>Title</th>
      <th>Story Summary</th>
      <th>Story Posted At</th>
      <th>Story Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  </div>
  

  <tbody>
    <% @newsvilles.each do |newsville| %>
      <tr>
        <td><%= link_to "Original Story", newsville.title_url, :target => "_blank" %></td>
        <td><%= newsville.title %></td>
        <td><%= newsville.body %></td>
        <td><%= newsville.created_at.strftime("%A, %d %b %Y %l:%M %p") %></td>
        <% if newsville.image_url.present? %>
        <td><%= image_tag newsville.image_url %></td>
        <% else %>
        <td><%= image_tag 'nia.jpg' %></td>
        <% end %>
        <td><%= link_to 'Comment', newsville, class: "btn btn-success btn-xs" %></td>
        <% if can? :update, @newsville %>
        <td><%= link_to 'Edit', edit_newsville_path(newsville), class: "btn btn-warning btn-xs" %></td>
        <% end %>
        <% if can? :destroy, @newsville %>
        <td><%= link_to 'Destroy', newsville, method: :delete, 
        data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-xs" %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<div class='text-center'>
  <%= will_paginate @newsvilles, renderer: BootstrapPagination::Rails %>
</div>

<br>

app/views/newsvilles/show.html.erb
<p id="notice"><%= notice %></p>


<div class='pull-left padding'>
  <% if @newsville.image_url.present? %>
  <td><%= image_tag @newsville.image_url, class: "img-rounded" %></td>
  <% else %>
  <td><%= image_tag 'nia.jpg', class: "img-rounded" %></td>
  <% end %>
</div> 

<p>
  <strong>View:</strong>
  <%= link_to "Original Story", @newsville.title_url, :target => "_blank" %>
</p>

<p>
  <strong>Headline:</strong>
  <%= @newsville.title %>
</p>

<p>
  <strong>Story Summary:</strong>
  <%= @newsville.body %>
</p>

<p>
  <strong>Posted:</strong>
  <%= time_ago_in_words(@newsville.created_at) %> ago 
</p>




<%= link_to 'Back to Newsvilles', newsvilles_path, class: 'btn btn-info btn-xs' %>
<hr>


<%= render @newsville.comments %>
 <%= simple_form_for [@newsville, Comment.new] do |comment| %>
   <%= comment.input :body, label: false, placeholder: 'Add your comment here.' %>
   <%= comment.submit "Add Comment", class: "btn btn-danger" %>
   <% end %>
   <hr>
   <%= link_to 'Back to Newsvilles', newsvilles_path, class: 'btn btn-info btn-xs' %>

app/views/pages/index.html.erb
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">World News At It's Best
            <small>Award Winning Coverage</small>
        </h1>
    </div>
</div>
<!-- /.row -->

<!-- Portfolio Item Row -->
<div class="row">

    <div class="col-md-8">
        <%= image_tag "bn.jpg", class: "img-rounded" %>
    </div>

<div class="col-md-4">
  <h3>Latest Comments</h3>
    <% @comments.each do |comment| %>
      <ul>
        <li><%= truncate(comment.body, length: 50) %></li>
      </ul>
    <% end %>        
</div>

</div>
<!-- /.row -->

<!-- Related Projects Row -->
<div class="row">

    <div class="col-lg-12">
        <h3 class="page-header">Breaking News</h3>
</div>
<% @newsvilles.each do |news| %>

<div class="panel panel-default col-md-3">
  <div class="panel-heading">
    <h3 class="panel-title"><%= link_to news.title, news %></h3>
  </div>
  <div class="panel-body text-center">
    <%= image_tag news.image_url %>
  </div>
</div>
<% end %>

</div>
<!-- /.row -->

<hr>